# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "v3" ]
    tags: ['3.*']
  pull_request:
    branches: [ "v3" ]

jobs:
  build-21:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.5.0

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew shadowJar

      - name: Upload JarFile
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: ./build/libs/NicoVideoPlayForVRC-3.0-SNAPSHOT-all.jar

  autotest1:
    needs: build-21
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Download JarFile
        uses: actions/download-artifact@v4
        with:
          name: jar

      - name: Run the Application
        run: java -jar ./NicoVideoPlayForVRC-3.0-SNAPSHOT-all.jar &
        shell: bash

      - name: Wait for the application to start
        run: sleep 1

      - name: Create config.yml Test
        run: |
          if [ -f ./config.yml ]; then
            echo "OK"
          else 
            exit 1
          fi
        shell: bash

  autotest2:
    needs: build-21
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Download JarFile
        uses: actions/download-artifact@v4
        with:
          name: jar

      - name: Run the Application
        run: java -jar ./NicoVideoPlayForVRC-3.0-SNAPSHOT-all.jar --default-config-mode &
        shell: bash

      - name: Create LogFolder Test
        run: |
          if [ -d ./log ]; then
            echo "OK"
          else
            exit 1
          fi
        shell: bash

  autotest3:
    needs: build-21
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Download JarFile
        uses: actions/download-artifact@v4
        with:
          name: jar

      - name: Run the Application
        run: java -jar ./NicoVideoPlayForVRC-3.0-SNAPSHOT-all.jar --default-config-mode &
        shell: bash

      - name: URL Request Test
        run: |
          HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:25252/?url=https://www.nicovideo.jp/watch/sm9)
          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "Expected HTTP status 200 but got $HTTP_STATUS"
            exit 1
          fi
        shell: bash

  release:
    needs: [autotest1, autotest2, autotest3]
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Download JarFile
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/download-artifact@v4
        with:
          name: jar

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: v${{ github.ref }}
          body: |
              - 作り直し(ニコ動のみ対応)
          draft: false
          prerelease: true

      - name: Upload JarFile
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./NicoVideoPlayForVRC-3.0-SNAPSHOT-all.jar
          asset_name: NicoVideoPlayForVRC-3.0-SNAPSHOT-all.jar
          asset_content_type: application/java-archive