on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: v${{ github.ref }}
          body: |
            - UDP通信にIDを追加して同じIDから2度目の通信が来たときはBad Request扱いとするように
            - 他処理鯖へ送信する順番をリスト順に
            - ニコ生(Re:仮)での不具合修正
            - OPENRECでの不具合修正
          draft: false
          prerelease: false